name: Предложение
description: Новая функция или улучшение
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу решает
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Как это должно работать
  - type: dropdown
    id: platform
    attributes:
      label: Где нужно
      multiple: true
      options: [Телефон, Android TV, Библиотека / API]
